import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

interface InvoiceItem {
  product_name: string;
  quantity: number;
  unit_price: number;
  amount: number;
}

interface Invoice {
  id: number;
  invoice_number: string;
  customer_id: number;
  amount: number;
  tax_amount: number;
  total_amount: number;
  status: string;
  due_date: string;
  created_at: string;
  customers?: {
    name: string;
    email: string;
  };
}

export const generateInvoicePDF = async (invoice: Invoice, items: InvoiceItem[]) => {
  const pdf = new jsPDF();
  
  // Company Header
  pdf.setFontSize(20);
  pdf.setTextColor(30, 64, 175); // Blue color
  pdf.text('AsaanKhaata', 20, 20);
  
  pdf.setFontSize(10);
  pdf.setTextColor(100, 100, 100);
  pdf.text('Developed by HH Developers', 20, 28);
  pdf.text('hussainahmadbilal@gmail.com', 20, 34);
  
  // Invoice Header
  pdf.setFontSize(24);
  pdf.setTextColor(0, 0, 0);
  pdf.text('INVOICE', 160, 20);
  
  pdf.setFontSize(10);
  pdf.text(`Invoice #: ${invoice.invoice_number}`, 160, 30);
  pdf.text(`Date: ${new Date(invoice.created_at).toLocaleDateString()}`, 160, 36);
  pdf.text(`Due Date: ${new Date(invoice.due_date).toLocaleDateString()}`, 160, 42);
  
  // Status
  const statusColor = invoice.status === 'paid' ? [34, 197, 94] : 
                     invoice.status === 'pending' ? [249, 115, 22] : [156, 163, 175];
  pdf.setFillColor(statusColor[0], statusColor[1], statusColor[2]);
  pdf.rect(160, 48, 30, 8, 'F');
  pdf.setTextColor(255, 255, 255);
  pdf.text(invoice.status.toUpperCase(), 162, 53);
  
  // Customer Information
  pdf.setTextColor(0, 0, 0);
  pdf.setFontSize(12);
  pdf.text('Bill To:', 20, 60);
  pdf.setFontSize(10);
  pdf.text(invoice.customers?.name || 'N/A', 20, 68);
  pdf.text(invoice.customers?.email || 'N/A', 20, 74);
  
  // Line separator
  pdf.setDrawColor(200, 200, 200);
  pdf.line(20, 85, 190, 85);
  
  // Items Header
  pdf.setFontSize(10);
  pdf.setTextColor(0, 0, 0);
  pdf.text('Description', 20, 95);
  pdf.text('Qty', 120, 95);
  pdf.text('Unit Price', 140, 95);
  pdf.text('Amount', 170, 95);
  
  pdf.line(20, 98, 190, 98);
  
  // Items
  let yPosition = 108;
  items.forEach((item) => {
    pdf.text(item.product_name, 20, yPosition);
    pdf.text(item.quantity.toString(), 120, yPosition);
    pdf.text(`Rs. ${item.unit_price.toLocaleString()}`, 140, yPosition);
    pdf.text(`Rs. ${item.amount.toLocaleString()}`, 170, yPosition);
    yPosition += 8;
  });
  
  // Totals
  yPosition += 10;
  pdf.line(120, yPosition, 190, yPosition);
  yPosition += 10;
  
  pdf.text('Subtotal:', 140, yPosition);
  pdf.text(`Rs. ${invoice.amount.toLocaleString()}`, 170, yPosition);
  yPosition += 8;
  
  pdf.text('Tax:', 140, yPosition);
  pdf.text(`Rs. ${invoice.tax_amount.toLocaleString()}`, 170, yPosition);
  yPosition += 8;
  
  pdf.setFontSize(12);
  pdf.setFont('bold');
  pdf.text('Total:', 140, yPosition);
  pdf.text(`Rs. ${invoice.total_amount.toLocaleString()}`, 170, yPosition);
  
  // Footer
  pdf.setFontSize(8);
  pdf.setFont('normal');
  pdf.setTextColor(100, 100, 100);
  pdf.text('Thank you for your business!', 20, 280);
  pdf.text('This invoice was generated by AsaanKhaata accounting system.', 20, 286);
  
  // Save the PDF
  pdf.save(`invoice-${invoice.invoice_number}.pdf`);
};

export const generateReportPDF = async (title: string, data: any[], columns: string[]) => {
  const pdf = new jsPDF();
  
  // Header
  pdf.setFontSize(16);
  pdf.setTextColor(30, 64, 175);
  pdf.text('AsaanKhaata', 20, 20);
  
  pdf.setFontSize(14);
  pdf.setTextColor(0, 0, 0);
  pdf.text(title, 20, 35);
  
  pdf.setFontSize(10);
  pdf.setTextColor(100, 100, 100);
  pdf.text(`Generated on: ${new Date().toLocaleString()}`, 20, 45);
  
  // Table headers
  let yPosition = 60;
  const columnWidth = 170 / columns.length;
  
  pdf.setFillColor(249, 250, 251);
  pdf.rect(20, yPosition - 5, 170, 10, 'F');
  
  pdf.setFontSize(9);
  pdf.setTextColor(0, 0, 0);
  columns.forEach((column, index) => {
    pdf.text(column, 20 + (index * columnWidth), yPosition);
  });
  
  yPosition += 10;
  pdf.line(20, yPosition, 190, yPosition);
  yPosition += 5;
  
  // Table data
  data.forEach((row) => {
    if (yPosition > 270) { // New page if needed
      pdf.addPage();
      yPosition = 20;
    }
    
    columns.forEach((column, index) => {
      const value = row[column.toLowerCase().replace(' ', '_')] || '';
      pdf.text(String(value), 20 + (index * columnWidth), yPosition);
    });
    yPosition += 8;
  });
  
  // Save
  pdf.save(`${title.toLowerCase().replace(/\s+/g, '-')}-report.pdf`);
};